### ISSUE TITLE
Sürekli dosya üretim hatası

### ISSUE THREAD

**Issue by ulascanerturk** [saltun/sCache#4]
Merhaba,
Script sürekli cache dosyası üretiyor. Her giren kullanıcı için yeni bir dosya üretiyor. Local'de bir problem yok ama sunucuya atınca böyle bir problem oluyor. Sizce neden kaynaklanıyor olabilir?

**Comment by saltun** [comment]
Merhabalar,
Sunucuda ki yazma okuma izinleri kaynaklı olabilir.

**Comment by Taiizor** [comment]
bazen verilen süre geçmese bile yine de cache üretiliyor. buna engel olamıyoruz

**Comment by ulascanerturk** [comment]
cache klasörünün ve alt dosyaların izinlerini yazılabilir olarak ayarladığınız zaman çözülüyor. Ben de artık cahce üretimi olmuyor. Var olan cache dosyalarının üzerinde yazılıyor.

**Comment by saltun** [comment]
> bazen verilen süre geçmese bile yine de cache üretiliyor. buna engel olamıyoruz



> cache klasörünün ve alt dosyaların izinlerini yazılabilir olarak ayarladığınız zaman çözülüyor. Ben de artık cahce üretimi olmuyor. Var olan cache dosyalarının üzerinde yazılıyor.

Sanırım dediğim gibi gibi yazma ve okuma izinleri ile kaynaklı @ulascanerturk ün dediğini dener misiniz ?

**Comment by Taiizor** [comment]
tamamdır, sorun ortadan kalktı asjdjasd

**Comment by Taiizor** [comment]
küçük bir yenilik olarak ise mesela şu yapılabilir.
options dizisine cachelencek sayfa tipi eklenebilir (image,json) gibi.
sayfalar cacheden çekildiği zaman o tür sayfalarda gözükür.
header('Content-Type: application/json');
header('Content-Type: image/png');
vs vs.

**Comment by saltun** [comment]
Önerinizi not aldım sorun çözüldüğüne göre kapatıyorum iyi çalışmalar.
